#! /bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/chilli
DAEMON_ARGS="--coaport 3779 --conf /etc/chilli.conf"
NAME=chilli
DESC=chilli
MACLIST=/usr/local/bin/hotspot/maclist.php
CLSLOG=/usr/local/bin/hotspot/psql.pl
CLSLOG2=/usr/local/bin/hotspot/clearlog.php
SQUID_IMPORT=php /usr/local/bin/hotspot/mysar/bin/mysar-importer.php
CHUNSTOP=/usr/local/bin/hotspot/chilli_unstop.sh

START_CHILLI=1

if [ -f /etc/default/chilli ] ; then
   . /etc/default/chilli
fi

if [ "$START_CHILLI" != "1" ] ; then
   echo "Chilli default off. Look at /etc/default/chilli"
   exit 0
fi

test -f $DAEMON || exit 0

. /etc/chilli/functions

MULTI=$(ls /etc/chilli/*/chilli.conf 2>/dev/null)
[ -z "$DHCPIF" ] && [ -n "$MULTI" ] && {
    for c in $MULTI; 
    do
	echo "Found configuration $c"
	DHCPIF=$(basename $(echo $c|sed 's#/chilli.conf##'))
	export DHCPIF
	echo "Running DHCPIF=$DHCPIF $0 $*"
	sh $0 $*
    done
    exit
}

if [ -n "$DHCPIF" ]; then
    CONFIG=/etc/chilli/$DHCPIF/chilli.conf
else
    CONFIG=/etc/chilli.conf
fi

[ -f $CONFIG ] || {
    echo "$CONFIG Not found"
    exit 0
}

check_required

RETVAL=0
prog="chilli"

case "$1" in
  start)
	echo -n "Starting $DESC: "
	/sbin/modprobe tun >/dev/null 2>&1
	echo 1 > /proc/sys/net/ipv4/ip_forward
	
	crontab -l 2>&- | grep -v $MACLIST | crontab -
	crontab -l 2>&- | grep -v $CLSLOG | crontab -
	crontab -l 2>&- | grep -v $SQUID_IMPORT | crontab -
	crontab -l 2>&- | grep -v $CLSLOG2 | crontab -
	crontab -l 2>&- | grep -v $CHUNSTOP | crontab -
	crontab -1 2>&- | /bin/echo 3 > /proc/sys/vm/drop_caches | crontab -
	echo "* * * * * $MACLIST" >> /var/spool/cron/crontabs/root
	echo "@daily $CLSLOG" >> /var/spool/cron/crontabs/root
	echo "0 */3 * * * $SQUID_IMPORT" >> /var/spool/cron/crontabs/root
	echo "@daily $CLSLOG2" >> /var/spool/cron/crontabs/root
	echo "* * * * * $CHUNSTOP" >> /var/spool/cron/crontabs/root
	echo "* */3 * * * /bin/echo 3 > /proc/sys/vm/drop_caches" >> /var/spool/cron/crontabs/root

	writeconfig
	radiusconfig

	test ${HS_ADMINTERVAL:-0} -gt 0 && {	
            (crontab -l 2>&- | grep -v $0
		echo "*/$HS_ADMINTERVAL * * * * $0 radconfig"
		) | crontab - 2>&-
	}

	ifconfig $HS_LANIF 0.0.0.0

	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.$HS_LANIF.pid \
		--exec $DAEMON -- -c $CONFIG
	RETVAL=$?
	echo "$NAME."
	;;
    
    checkrunning)
	check=`start-stop-daemon --start --exec $DAEMON --test`
	if [ x"$check" != x"$DAEMON already running." ] ; then
            $0 start
	fi
	;;
    
    radconfig)
	[ -e $MAIN_CONF ] || writeconfig
	radiusconfig
	;;
    
    restart)
	$0 stop
	sleep 1
	$0 start
	RETVAL=$?
	;;
    
    stop)
	echo -n "Stopping $DESC: "
	
	crontab -l 2>&- | grep -v $0 | crontab -
	
	start-stop-daemon --oknodo --stop --quiet --pidfile /var/run/$NAME.$HS_LANIF.pid \
	    --exec $DAEMON
	echo "$NAME."
	;;
    
    reload)
	echo "Reloading $DESC."
	start-stop-daemon --stop --signal 1 --quiet --pidfile \
	    /var/run/$NAME.$HS_LANIF.pid --exec $DAEMON
	;;
    
    condrestart)
	check=`start-stop-daemon --start --exec $DAEMON --test`
	if [ x"$check" != x"$DAEMON already running." ] ; then
            $0 restart
            RETVAL=$?
	fi
	;;
    
    status)
	status chilli
	RETVAL=$?
	;;
    
    *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|condrestart|status|reload|radconfig}" >&2
	exit 1
	;;
esac

exit 0
